### ISSUE TITLE
Unable to run default server

### ISSUE THREAD

**Issue by trevorturk** [socketry/async-job-adapter-active_job#2]
In the guides, I wasn't able to get this part working: https://socketry.github.io/async-job-adapter-active_job/guides/getting-started/index#running-a-server but I was able to follow the example. Perhaps we can just add an example to the README or guides?

**Comment by ioquatix** [comment]
I included `async-job-adapter-active_job-server` which may be more convenient.

**Comment by ioquatix** [comment]
Please check https://github.com/socketry/async-job-rails-example where I've confirmed it's working.
