### ISSUE TITLE
Consider not automatically setting config.active_job.queue_adapter

### ISSUE THREAD

**Issue by trevorturk** [socketry/async-job-adapter-active_job#3]
I believe this is happening in: https://github.com/socketry/async-job-adapter-active_job/blob/main/lib/async/job/adapter/active_job/railtie.rb#L89 to save some config, but FWIW I'd prefer to set this myself, so I can have multiple job processors configured at once, or configured on the fly with an ENV var etc. 

```ruby
config.active_job.queue_adapter = :sidekiq
# ...becomes
config.active_job.queue_adapter = :async_job
```

**Comment by ioquatix** [comment]
https://github.com/rails/rails/blob/136d0c2eb0d29c86d012e32a3dc26afa90b24cbd/activejob/lib/active_job/queue_adapter.rb#L46-L62

Using a symbol requires us to go via this code path.

Not sure if there is an easy way to make it optional... not possible to have multiple job processors as a queue adapter... ActiveJob is a bit limited in this regard.

**Comment by trevorturk** [comment]
I'm not sure if this is helpful, but it might be worth checking: https://github.com/bensheldon/good_job/pull/28 -- note the PR comments link to where Rails talks about not adding more adapters, but you can see with GoodJob they did figure out how to allow a typical looking config via symbol. I think then you'd have to add `async-job` specific options, which GoodJob also does (see https://github.com/bensheldon/good_job?tab=readme-ov-file#configuration-options in the README.)

**Comment by ioquatix** [comment]
Yes, this looks like a good option.

**Comment by ioquatix** [comment]
After reviewing this in greater detail, I realise my earlier assumption was wrong. Any job can have a custom queue_adapter and queue_to (name). This gives us a great deal of flexibility. However, it's still important to define queues and aliases up front. I'll change the implementation.
