### ISSUE TITLE
Consider not retrying jobs by default

### ISSUE THREAD

**Issue by trevorturk** [socketry/async-job-adapter-active_job#4]
I'm not 100% sure, but I think all ActiveJob adapters are supposed to disable automatic retry and only enable if configured, see: https://edgeguides.rubyonrails.org/active_job_basics.html#retrying-or-discarding-failed-jobs -- but perhaps at least documentation about how to disable would be good. (Perhaps just `discard_on StandardError` or so would be enough?)

**Comment by ioquatix** [comment]
We now ignore ActiveJob failures - i.e. ActiveJob is responsible for retrying OR logging:

https://github.com/socketry/async-job-adapter-active_job/blob/main/lib/async/job/adapter/active_job/executor.rb#L21-L27
