### ISSUE TITLE
Consider allowing symbols in config.async_job.backend_for

### ISSUE THREAD

**Issue by trevorturk** [socketry/async-job-adapter-active_job#5]
I'd love to have strings/symbols be interchangeable, but perhaps in the mean time a symbol should throw an argument error if not a string, for example here it took me a while to debug what I'd done wrong:

```ruby
config.async_job.backend_for :default do
  # :default needs to be "default" as a string, not a symbol, or it's ignored
end 
```

**Comment by ioquatix** [comment]
`backend_for` is renamed `define_queue`.

ActiveJob uses strings for queue names, so let's validate it.
